import { stageColors } from "../format";
import type { AppState } from "../types";

export const STORE_KEY = "genecthub-state-v4";

export const seed: AppState = {
  usuarioId: "u-admin",
  usuarios: [
    {
      id: "u-admin",
      nome: "Marina Alves",
      email: "marina@genect.com",
      role: "admin",
    },
    {
      id: "u-faccao",
      nome: "Facção Silva",
      email: "silva@faccao.com",
      role: "terceirizado",
      terceirizadoId: "ter-silva",
    },
  ],
  empresas: [
    { id: "emp-genect", nome: "Genect Confecções", ativa: true },
    { id: "emp-atelier", nome: "Atelier Norte", ativa: true },
    { id: "emp-inativa", nome: "Linha Antiga Ltda", ativa: false },
  ],
  clientes: [
    { id: "cli-aurora", nome: "Loja Aurora", ativo: true },
    { id: "cli-leste", nome: "Magazine Leste", ativo: true },
    { id: "cli-casa", nome: "Casa Brava Atacado", ativo: true },
  ],
  fornecedores: [
    {
      id: "for-malharia",
      razaoSocial: "Malharia Horizonte Ltda",
      contato: "11 4002-1000",
      ativo: true,
    },
    {
      id: "for-aviamentos",
      razaoSocial: "Aviamentos Central",
      contato: "11 3221-8800",
      ativo: true,
    },
  ],
  terceirizados: [
    {
      id: "ter-silva",
      nome: "Facção Silva",
      especialidade: "Montagem e costura plana",
      valorPorPeca: 5,
      ativo: true,
    },
    {
      id: "ter-ana",
      nome: "Costura da Ana",
      especialidade: "Overloque e galoneira",
      valorPorPeca: 4.2,
      ativo: true,
    },
    {
      id: "ter-norte",
      nome: "Facção Norte",
      especialidade: "Calça e jeans",
      valorPorPeca: 6.5,
      ativo: true,
    },
  ],
  insumos: [
    {
      id: "ins-malha",
      codigo: "TEC-MAL-CAN-01",
      descricao: "Malha Canelada Supreme 96% Algodão 4% Elastano",
      categoria: "tecido",
      unidadeCompra: "kg",
      unidadeConsumo: "m",
      fatorConversao: 2.4,
      estoqueMinimo: 80,
      custoMedio: 42.9,
      estoqueAtual: 186,
      reservado: 72,
      fornecedorId: "for-malharia",
      refFornecedor: "HZ-CAN-9604",
    },
    {
      id: "ins-viscose",
      codigo: "TEC-VIS-LISO-02",
      descricao: "Viscose Lisa 140 g/m² Preto",
      categoria: "tecido",
      unidadeCompra: "m",
      unidadeConsumo: "m",
      fatorConversao: 1,
      estoqueMinimo: 120,
      custoMedio: 18.5,
      estoqueAtual: 340,
      reservado: 90,
      fornecedorId: "for-malharia",
      refFornecedor: "HZ-VIS-140",
    },
    {
      id: "ins-jeans",
      codigo: "TEC-JNS-STR-03",
      descricao: "Jeans Stretch 11 oz Indigo",
      categoria: "tecido",
      unidadeCompra: "m",
      unidadeConsumo: "m",
      fatorConversao: 1,
      estoqueMinimo: 60,
      custoMedio: 27.4,
      estoqueAtual: 95,
      reservado: 48,
      fornecedorId: "for-malharia",
      refFornecedor: "HZ-JNS-11",
    },
    {
      id: "ins-ziper",
      codigo: "AVI-ZIP-INV-50",
      descricao: "Zíper Invisível 50 cm Preto",
      categoria: "ziper",
      unidadeCompra: "un",
      unidadeConsumo: "un",
      fatorConversao: 1,
      estoqueMinimo: 400,
      custoMedio: 1.15,
      estoqueAtual: 1280,
      reservado: 300,
      fornecedorId: "for-aviamentos",
      refFornecedor: "AC-ZIP-50P",
    },
    {
      id: "ins-botao",
      codigo: "AVI-BTN-POL-18",
      descricao: "Botão Poliéster 18 mm Pérola",
      categoria: "botao",
      unidadeCompra: "cx",
      unidadeConsumo: "un",
      fatorConversao: 144,
      estoqueMinimo: 20,
      custoMedio: 18,
      estoqueAtual: 64,
      reservado: 8,
      fornecedorId: "for-aviamentos",
      refFornecedor: "AC-BTN-18",
    },
    {
      id: "ins-etiqueta",
      codigo: "AVI-ETQ-COMP-01",
      descricao: "Etiqueta de composição 25 mm",
      categoria: "etiqueta",
      unidadeCompra: "milheiro",
      unidadeConsumo: "un",
      fatorConversao: 1000,
      estoqueMinimo: 5,
      custoMedio: 42,
      estoqueAtual: 12,
      reservado: 1.2,
      fornecedorId: "for-aviamentos",
      refFornecedor: "AC-ETQ-25",
    },
    {
      id: "ins-linha",
      codigo: "AVI-LIN-COSE-120",
      descricao: "Linha de costura 120 cone 5.000 m",
      categoria: "linha",
      unidadeCompra: "cone",
      unidadeConsumo: "m",
      fatorConversao: 5000,
      estoqueMinimo: 30,
      custoMedio: 9.8,
      estoqueAtual: 74,
      reservado: 6,
      fornecedorId: "for-aviamentos",
      refFornecedor: "AC-LIN-120",
    },
  ],
  lotes: [
    {
      id: "lot-malha-a",
      insumoId: "ins-malha",
      loteFabricante: "BANHO-4412",
      quantidade: 120,
      quantidadeRestante: 84,
      preco: 41.5,
      unidade: "kg",
      nf: "NF-88321",
      dataEntrada: "2026-09-12",
      fornecedorId: "for-malharia",
    },
    {
      id: "lot-malha-b",
      insumoId: "ins-malha",
      loteFabricante: "BANHO-4490",
      quantidade: 90,
      quantidadeRestante: 90,
      preco: 44.1,
      unidade: "kg",
      nf: "NF-88402",
      dataEntrada: "2026-09-18",
      fornecedorId: "for-malharia",
    },
    {
      id: "lot-viscose",
      insumoId: "ins-viscose",
      loteFabricante: "TING-2201",
      quantidade: 400,
      quantidadeRestante: 340,
      preco: 18.5,
      unidade: "m",
      nf: "NF-88390",
      dataEntrada: "2026-09-10",
      fornecedorId: "for-malharia",
    },
    {
      id: "lot-jeans",
      insumoId: "ins-jeans",
      loteFabricante: "IND-1188",
      quantidade: 150,
      quantidadeRestante: 95,
      preco: 27.4,
      unidade: "m",
      nf: "NF-88211",
      dataEntrada: "2026-09-04",
      fornecedorId: "for-malharia",
    },
  ],
  produtos: [
    {
      id: "prod-vestido",
      referencia: "REF-452",
      nome: "Vestido Midi Regata",
      tipoNegocio: "fabricacao",
      categoria: "Feminino > Vestidos > Casual",
      linha: "Verão 26",
      cores: ["Preto", "Off-white", "Terracota"],
      tamanhos: ["P", "M", "G", "GG"],
      materiaPrimaId: "ins-viscose",
      consumoTecidoPorPeca: 1.8,
      aviamentos: [
        { insumoId: "ins-ziper", consumoPorPeca: 1 },
        { insumoId: "ins-etiqueta", consumoPorPeca: 1 },
        { insumoId: "ins-linha", consumoPorPeca: 45 },
      ],
      roteiro: [
        { id: "r1", nome: "Corte", kind: "corte", minutos: 4 },
        { id: "r2", nome: "Costura", kind: "costura", minutos: 22 },
        { id: "r3", nome: "Caseado", kind: "acabamento", minutos: 6 },
        { id: "r4", nome: "Revisão", kind: "revisao", minutos: 5 },
        { id: "r5", nome: "Embalagem", kind: "embalagem", minutos: 3 },
      ],
      custoEstimado: 38.4,
      precoVenda: 89,
      fotoHint: "Midi regata evasê",
    },
    {
      id: "prod-camiseta",
      referencia: "REF-118",
      nome: "Camiseta Oversize",
      tipoNegocio: "servico",
      categoria: "Unissex > Camisetas > Básico",
      linha: "Essencial",
      cores: ["Preto", "Branco", "Verde musgo"],
      tamanhos: ["P", "M", "G", "GG", "XGG"],
      materiaPrimaId: "ins-malha",
      consumoTecidoPorPeca: 0.55,
      aviamentos: [
        { insumoId: "ins-etiqueta", consumoPorPeca: 1 },
        { insumoId: "ins-linha", consumoPorPeca: 28 },
      ],
      roteiro: [
        { id: "c1", nome: "Corte", kind: "corte", minutos: 2 },
        { id: "c2", nome: "Costura", kind: "costura", minutos: 12 },
        { id: "c3", nome: "Revisão", kind: "revisao", minutos: 3 },
        { id: "c4", nome: "Embalagem", kind: "embalagem", minutos: 2 },
      ],
      custoEstimado: 18.9,
      precoVenda: 42,
      fotoHint: "Oversize gola careca",
    },
    {
      id: "prod-calca",
      referencia: "REF-307",
      nome: "Calça Wide Leg",
      tipoNegocio: "fabricacao",
      categoria: "Feminino > Calças > Casual",
      linha: "Inverno 26",
      cores: ["Indigo", "Preto"],
      tamanhos: ["38", "40", "42", "44", "46"],
      materiaPrimaId: "ins-jeans",
      consumoTecidoPorPeca: 1.6,
      aviamentos: [
        { insumoId: "ins-botao", consumoPorPeca: 1 },
        { insumoId: "ins-ziper", consumoPorPeca: 1 },
        { insumoId: "ins-etiqueta", consumoPorPeca: 1 },
        { insumoId: "ins-linha", consumoPorPeca: 80 },
      ],
      roteiro: [
        { id: "p1", nome: "Corte", kind: "corte", minutos: 6 },
        { id: "p2", nome: "Terceirizado", kind: "faccao", minutos: 38 },
        { id: "p3", nome: "Revisão", kind: "revisao", minutos: 8 },
        { id: "p4", nome: "Embalagem", kind: "embalagem", minutos: 4 },
      ],
      custoEstimado: 52,
      precoVenda: 129,
      fotoHint: "Wide leg cintura alta",
    },
  ],
  boardNodes: [
    { id: "st-recebimento", kind: "recebimento", label: "Recebimento", color: stageColors.recebimento, x: 24, y: 170 },
    { id: "st-corte", kind: "corte", label: "Corte", color: stageColors.corte, x: 300, y: 40 },
    { id: "st-faccao", kind: "faccao", label: "Facção Silva", color: stageColors.faccao, x: 580, y: 0 },
    { id: "st-costura", kind: "costura", label: "Costura interna", color: stageColors.costura, x: 580, y: 300 },
    { id: "st-revisao", kind: "revisao", label: "Revisão", color: stageColors.revisao, x: 860, y: 40 },
    { id: "st-embalagem", kind: "embalagem", label: "Embalagem", color: stageColors.embalagem, x: 860, y: 320 },
    { id: "st-expedicao", kind: "expedicao", label: "Expedição", color: stageColors.expedicao, x: 1140, y: 170 },
  ],
  boardEdges: [
    { id: "e1", source: "st-recebimento", target: "st-corte" },
    { id: "e2", source: "st-corte", target: "st-faccao" },
    { id: "e3", source: "st-corte", target: "st-costura" },
    { id: "e4", source: "st-faccao", target: "st-revisao" },
    { id: "e5", source: "st-costura", target: "st-revisao" },
    { id: "e6", source: "st-revisao", target: "st-embalagem" },
    { id: "e7", source: "st-embalagem", target: "st-expedicao" },
  ],
  ops: [
    {
      id: "op-1",
      numero: "OP-24091",
      dataEntrada: "2026-09-18",
      empresaId: "emp-genect",
      clienteId: "cli-aurora",
      produtoId: "prod-vestido",
      tipoNegocio: "fabricacao",
      cor: "Terracota",
      quantidade: 400,
      precoUnitario: 89,
      observacoes: "Prioridade vitrine. Manter lote único de viscose.",
      terceirizadoIds: ["ter-silva"],
      valorServicoPorPeca: 5,
      quantidadeProduzida: 210,
      perdas: 6,
      refugo: 4,
      lotesInsumo: [{ loteId: "lot-viscose", quantidade: 720 }],
      atados: [
        { id: "at-1a", codigo: "AT-24091-01", quantidade: 50, terceirizadoId: "ter-silva", stageId: "st-faccao", status: "em_setor" },
        { id: "at-1b", codigo: "AT-24091-02", quantidade: 50, terceirizadoId: "ter-silva", stageId: "st-faccao", status: "em_setor" },
        { id: "at-1c", codigo: "AT-24091-03", quantidade: 50, stageId: "st-corte", status: "aberto" },
        { id: "at-1d", codigo: "AT-24091-04", quantidade: 50, stageId: "st-corte", status: "aberto" },
      ],
      status: "em_producao",
      stageId: "st-corte",
      createdAt: "2026-09-18T09:10:00.000Z",
    },
    {
      id: "op-1b",
      numero: "OP-24091-A",
      dataEntrada: "2026-09-19",
      empresaId: "emp-genect",
      clienteId: "cli-aurora",
      produtoId: "prod-vestido",
      tipoNegocio: "fabricacao",
      cor: "Terracota",
      quantidade: 50,
      precoUnitario: 89,
      observacoes: "OP filha — atado enviado à Facção Silva.",
      terceirizadoIds: ["ter-silva"],
      valorServicoPorPeca: 5,
      quantidadeProduzida: 48,
      perdas: 1,
      refugo: 1,
      lotesInsumo: [{ loteId: "lot-viscose", quantidade: 90 }],
      parentOpId: "op-1",
      atados: [
        { id: "at-1e", codigo: "AT-24091-A1", quantidade: 50, terceirizadoId: "ter-silva", stageId: "st-faccao", status: "em_setor" },
      ],
      status: "em_producao",
      stageId: "st-faccao",
      createdAt: "2026-09-19T11:00:00.000Z",
    },
    {
      id: "op-2",
      numero: "OP-24092",
      dataEntrada: "2026-09-19",
      empresaId: "emp-genect",
      clienteId: "cli-leste",
      produtoId: "prod-camiseta",
      tipoNegocio: "servico",
      cor: "Verde musgo",
      quantidade: 800,
      precoUnitario: 42,
      observacoes: "Curva P/M pesada. Não misturar banhos 4412 e 4490.",
      terceirizadoIds: ["ter-ana"],
      valorServicoPorPeca: 4.2,
      quantidadeProduzida: 520,
      perdas: 18,
      refugo: 9,
      lotesInsumo: [{ loteId: "lot-malha-a", quantidade: 36 }],
      atados: [
        { id: "at-2a", codigo: "AT-24092-01", quantidade: 50, terceirizadoId: "ter-ana", stageId: "st-costura", status: "em_setor" },
        { id: "at-2b", codigo: "AT-24092-02", quantidade: 50, terceirizadoId: "ter-ana", stageId: "st-costura", status: "em_setor" },
      ],
      status: "em_producao",
      stageId: "st-costura",
      createdAt: "2026-09-19T08:40:00.000Z",
    },
    {
      id: "op-3",
      numero: "OP-24093",
      dataEntrada: "2026-09-16",
      empresaId: "emp-atelier",
      clienteId: "cli-casa",
      produtoId: "prod-calca",
      tipoNegocio: "fabricacao",
      cor: "Indigo",
      quantidade: 300,
      precoUnitario: 129,
      observacoes: "Facção Norte — jeans stretch.",
      terceirizadoIds: ["ter-norte"],
      valorServicoPorPeca: 6.5,
      quantidadeProduzida: 260,
      perdas: 8,
      refugo: 5,
      lotesInsumo: [{ loteId: "lot-jeans", quantidade: 480 }],
      atados: [
        { id: "at-3a", codigo: "AT-24093-01", quantidade: 50, terceirizadoId: "ter-norte", stageId: "st-revisao", status: "em_setor" },
      ],
      status: "revisao",
      stageId: "st-revisao",
      createdAt: "2026-09-16T14:20:00.000Z",
    },
    {
      id: "op-4",
      numero: "OP-24094",
      dataEntrada: "2026-09-15",
      empresaId: "emp-genect",
      clienteId: "cli-aurora",
      produtoId: "prod-vestido",
      tipoNegocio: "fabricacao",
      cor: "Off-white",
      quantidade: 150,
      precoUnitario: 89,
      observacoes: "",
      terceirizadoIds: ["ter-silva"],
      valorServicoPorPeca: 5,
      quantidadeProduzida: 146,
      perdas: 2,
      refugo: 2,
      lotesInsumo: [{ loteId: "lot-viscose", quantidade: 270 }],
      atados: [
        { id: "at-4a", codigo: "AT-24094-01", quantidade: 50, stageId: "st-embalagem", status: "concluido" },
      ],
      status: "em_producao",
      stageId: "st-embalagem",
      createdAt: "2026-09-15T10:00:00.000Z",
    },
    {
      id: "op-5",
      numero: "OP-24095",
      dataEntrada: "2026-09-21",
      empresaId: "emp-genect",
      clienteId: "cli-leste",
      produtoId: "prod-camiseta",
      tipoNegocio: "servico",
      cor: "Branco",
      quantidade: 200,
      precoUnitario: 42,
      observacoes: "Entrada do dia.",
      terceirizadoIds: [],
      valorServicoPorPeca: 4.2,
      quantidadeProduzida: 0,
      perdas: 0,
      refugo: 0,
      lotesInsumo: [{ loteId: "lot-malha-a", quantidade: 12 }],
      atados: [
        { id: "at-5a", codigo: "AT-24095-01", quantidade: 50, stageId: "st-recebimento", status: "aberto" },
        { id: "at-5b", codigo: "AT-24095-02", quantidade: 50, stageId: "st-recebimento", status: "aberto" },
        { id: "at-5c", codigo: "AT-24095-03", quantidade: 50, stageId: "st-recebimento", status: "aberto" },
        { id: "at-5d", codigo: "AT-24095-04", quantidade: 50, stageId: "st-recebimento", status: "aberto" },
      ],
      status: "aberta",
      stageId: "st-recebimento",
      createdAt: "2026-09-21T08:05:00.000Z",
    },
    {
      id: "op-6",
      numero: "OP-24080",
      dataEntrada: "2026-09-02",
      empresaId: "emp-genect",
      clienteId: "cli-casa",
      produtoId: "prod-camiseta",
      tipoNegocio: "servico",
      cor: "Preto",
      quantidade: 600,
      precoUnitario: 42,
      observacoes: "Encerrada. Faturada em parte.",
      terceirizadoIds: ["ter-ana"],
      valorServicoPorPeca: 4.2,
      quantidadeProduzida: 588,
      perdas: 8,
      refugo: 4,
      lotesInsumo: [{ loteId: "lot-malha-a", quantidade: 30 }],
      atados: [],
      status: "finalizada",
      stageId: "st-expedicao",
      createdAt: "2026-09-02T09:00:00.000Z",
    },
  ],
  contasPagar: [
    {
      id: "cp-1",
      empresaId: "emp-genect",
      descricao: "Acerto Facção Silva — OP-24091",
      origem: "faccao",
      origemId: "op-1",
      valor: 1050,
      vencimento: "2026-09-25",
      competencia: "2026-09",
      pagamentos: [],
    },
    {
      id: "cp-2",
      empresaId: "emp-genect",
      descricao: "Malharia Horizonte — NF-88402",
      origem: "compra",
      origemId: "lot-malha-b",
      valor: 3969,
      vencimento: "2026-09-30",
      competencia: "2026-09",
      pagamentos: [
        { id: "pg-1", valor: 1500, data: "2026-09-20", estornado: false },
      ],
    },
    {
      id: "cp-3",
      empresaId: "emp-atelier",
      descricao: "Aluguel ateliê",
      origem: "manual",
      valor: 4200,
      vencimento: "2026-09-10",
      competencia: "2026-09",
      pagamentos: [
        { id: "pg-2", valor: 4200, data: "2026-09-10", estornado: false },
      ],
    },
  ],
  contasReceber: [
    {
      id: "cr-1",
      empresaId: "emp-genect",
      clienteId: "cli-casa",
      descricao: "Faturamento OP-24080",
      origem: "faturamento",
      origemId: "fat-1",
      opId: "op-6",
      valor: 24696,
      vencimento: "2026-09-28",
      competencia: "2026-09",
      recebimentos: [
        { id: "rc-1", valor: 10000, data: "2026-09-18", estornado: false },
      ],
    },
  ],
  faturamentos: [
    {
      id: "fat-1",
      opId: "op-6",
      clienteId: "cli-casa",
      empresaId: "emp-genect",
      valor: 24696,
      data: "2026-09-12",
      competencia: "2026-09",
      contaReceberId: "cr-1",
    },
  ],
  orcamentos: [
    {
      id: "orc-1",
      empresaId: "emp-genect",
      competencia: "2026-09",
      status: "aprovado",
      receitaBruta: 180000,
      despesasVariaveis: 72000,
      despesasFixas: 38000,
      resultadoFinanceiro: -1200,
      tributos: 16200,
    },
    {
      id: "orc-2",
      empresaId: "emp-genect",
      competencia: "2026-08",
      status: "fechado",
      receitaBruta: 164000,
      despesasVariaveis: 69000,
      despesasFixas: 37500,
      resultadoFinanceiro: -800,
      tributos: 14760,
    },
  ],
  movimentos: [
    {
      id: "mv-1",
      tipo: "entrada",
      insumoId: "ins-malha",
      loteId: "lot-malha-b",
      quantidade: 90,
      data: "2026-09-18",
      nf: "NF-88402",
      nota: "Entrada de malha banho 4490",
    },
    {
      id: "mv-2",
      tipo: "reserva",
      insumoId: "ins-viscose",
      loteId: "lot-viscose",
      quantidade: 720,
      opId: "op-1",
      data: "2026-09-18",
      nota: "Reserva OP-24091",
    },
  ],
};
